//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraduationProjectBackend
{
    using System;
    using System.Collections.Generic;
    
    public partial class DangerList
    {
        public int MemberID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public Nullable<int> MemberUserID { get; set; }
    
        public virtual User User { get; set; }
        public virtual User DangerListMembrs { get; set; }
    }
}
