//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraduationProjectBackend
{
    using System;
    using System.Collections.Generic;
    
    public partial class Friend
    {
        public int FrinedshipID { get; set; }
        public int InitatiorUserID { get; set; }
        public Nullable<bool> RealTimeTrack { get; set; }
        public int RecieverUserID { get; set; }
    
        public virtual User InitiatorUID { get; set; }
        public virtual User RecieverUID { get; set; }
    }
}
