//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraduationProjectBackend
{
    using System;
    using System.Collections.Generic;
    
    public partial class RealTimeTrackRequest
    {
        public int RequestID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> FriendID { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<bool> State { get; set; }
    
        public virtual User User { get; set; }
        public virtual User Friend { get; set; }
    }
}
