//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraduationProjectBackend
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.FriendRequestsSent = new HashSet<FriendRequest>();
            this.FriendRequestsReceived = new HashSet<FriendRequest>();
            this.RealTimeTrackRequestsSent = new HashSet<RealTimeTrackRequest>();
            this.RealTimeTrackRequestsRecieved = new HashSet<RealTimeTrackRequest>();
            this.DangerList = new HashSet<DangerList>();
            this.DangerListMembers = new HashSet<DangerList>();
            this.FriendsIntiated = new HashSet<Friend>();
            this.FriendsRecieved = new HashSet<Friend>();
        }
    
        public int UserID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Password { get; set; }
        public Nullable<bool> LoggedIn { get; set; }
        public string ProfilePicture { get; set; }
    
        public virtual ICollection<FriendRequest> FriendRequestsSent { get; set; }
        public virtual ICollection<FriendRequest> FriendRequestsReceived { get; set; }
        public virtual ICollection<RealTimeTrackRequest> RealTimeTrackRequestsSent { get; set; }
        public virtual ICollection<RealTimeTrackRequest> RealTimeTrackRequestsRecieved { get; set; }
        public virtual ICollection<DangerList> DangerList { get; set; }
        public virtual ICollection<DangerList> DangerListMembers { get; set; }
        public virtual ICollection<Friend> FriendsIntiated { get; set; }
        public virtual ICollection<Friend> FriendsRecieved { get; set; }
    }
}
