//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraduationProjectBackend
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.FriendRequests = new HashSet<FriendRequest>();
            this.FriendRequests1 = new HashSet<FriendRequest>();
            this.RealTimeTrackRequests = new HashSet<RealTimeTrackRequest>();
            this.RealTimeTrackRequests1 = new HashSet<RealTimeTrackRequest>();
        }
    
        public int UserID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Password { get; set; }
        public Nullable<bool> LoggedIn { get; set; }
        public string ProfilePicture { get; set; }
    
        public virtual ICollection<FriendRequest> FriendRequests { get; set; }
        public virtual ICollection<FriendRequest> FriendRequests1 { get; set; }
        public virtual ICollection<RealTimeTrackRequest> RealTimeTrackRequests { get; set; }
        public virtual ICollection<RealTimeTrackRequest> RealTimeTrackRequests1 { get; set; }
    }
}
